## NumPy for matplotlib & Seaborn
### ndarray - n-dimensional array, data structure

In [4]:
import numpy as np
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
a[0]

array([0, 1, 2, 3, 4])

In [8]:
a[3][4]

np.int64(19)

In [10]:
a.ndim

2

In [12]:
a.dtype

dtype('int64')

In [14]:
a.size

20

In [20]:
a.shape # i.e. in this example (4, 5) is four rows with 5 integers

(4, 5)

In [22]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [28]:
c= np.arange(1,20,2)
print(c)

[ 1  3  5  7  9 11 13 15 17 19]


In [32]:
d = np.linspace(0,20,100)
print(d)

[ 0.          0.2020202   0.4040404   0.60606061  0.80808081  1.01010101
  1.21212121  1.41414141  1.61616162  1.81818182  2.02020202  2.22222222
  2.42424242  2.62626263  2.82828283  3.03030303  3.23232323  3.43434343
  3.63636364  3.83838384  4.04040404  4.24242424  4.44444444  4.64646465
  4.84848485  5.05050505  5.25252525  5.45454545  5.65656566  5.85858586
  6.06060606  6.26262626  6.46464646  6.66666667  6.86868687  7.07070707
  7.27272727  7.47474747  7.67676768  7.87878788  8.08080808  8.28282828
  8.48484848  8.68686869  8.88888889  9.09090909  9.29292929  9.49494949
  9.6969697   9.8989899  10.1010101  10.3030303  10.50505051 10.70707071
 10.90909091 11.11111111 11.31313131 11.51515152 11.71717172 11.91919192
 12.12121212 12.32323232 12.52525253 12.72727273 12.92929293 13.13131313
 13.33333333 13.53535354 13.73737374 13.93939394 14.14141414 14.34343434
 14.54545455 14.74747475 14.94949495 15.15151515 15.35353535 15.55555556
 15.75757576 15.95959596 16.16161616 16.36363636 16

In [34]:
d = np.linspace(0,20,100).reshape(10,10)
print(d)

[[ 0.          0.2020202   0.4040404   0.60606061  0.80808081  1.01010101
   1.21212121  1.41414141  1.61616162  1.81818182]
 [ 2.02020202  2.22222222  2.42424242  2.62626263  2.82828283  3.03030303
   3.23232323  3.43434343  3.63636364  3.83838384]
 [ 4.04040404  4.24242424  4.44444444  4.64646465  4.84848485  5.05050505
   5.25252525  5.45454545  5.65656566  5.85858586]
 [ 6.06060606  6.26262626  6.46464646  6.66666667  6.86868687  7.07070707
   7.27272727  7.47474747  7.67676768  7.87878788]
 [ 8.08080808  8.28282828  8.48484848  8.68686869  8.88888889  9.09090909
   9.29292929  9.49494949  9.6969697   9.8989899 ]
 [10.1010101  10.3030303  10.50505051 10.70707071 10.90909091 11.11111111
  11.31313131 11.51515152 11.71717172 11.91919192]
 [12.12121212 12.32323232 12.52525253 12.72727273 12.92929293 13.13131313
  13.33333333 13.53535354 13.73737374 13.93939394]
 [14.14141414 14.34343434 14.54545455 14.74747475 14.94949495 15.15151515
  15.35353535 15.55555556 15.75757576 15.95959596]


In [36]:
e = np.random.rand(4,4)
print(e)

[[0.33486483 0.61658394 0.57186178 0.73440817]
 [0.70171993 0.61155588 0.41745077 0.14249104]
 [0.14772412 0.36194021 0.44050564 0.30830793]
 [0.18508402 0.68992787 0.00685153 0.13737047]]
