In [33]:
import numpy as np

np_arr = np.array([[1,2],[6,8]])
print(np_arr)
print(np_arr.shape)

np_arr_insert= np.insert(arr=np_arr, obj=1, values=[3,4], axis=0)
print(np_arr_insert)

np_arr_append = np.append(arr=np_arr,values=[3,4])
print(np_arr_append)

np_arr_append = np.append(arr=np_arr,values=[[3,4],[1,2]])
print(np_arr_append)

np_arr_delete = np.delete(arr=np_arr,obj=0,axis=0)
print(np_arr_delete)

[[1 2]
 [6 8]]
(2, 2)
[[1 2]
 [3 4]
 [6 8]]
[1 2 6 8 3 4]
[1 2 6 8 3 4 1 2]
[[6 8]]


In [27]:
print(np_arr>2)

[[False False]
 [ True  True]]


In [61]:
np_arr = np.array([[1,5,2],[4,1,6],[2,4,10]])
np_cond = np_arr[np_arr>3]
print(np_cond)
print(np_arr>3)

[ 5  4  6  4 10]
[[False  True False]
 [ True False  True]
 [False  True  True]]
